/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author donHarumi4
 */

import dao.PelangganDAO;
import dao.ReservasiDAO;
import dao.RoomDAO;
import model.Pelanggan;
import model.Reservasi;
import model.User;
import util.KoneksiDB;

import java.math.BigDecimal;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Room;

public class FormBooking extends javax.swing.JFrame {
    
    private ReservasiDAO reservasiDAO = new ReservasiDAO();
    private RoomDAO roomDAO = new RoomDAO();
    private final User currentUser;
    private Pelanggan pelanggan;


    /**
     * Creates new form ReservationForm
     * @param user
     */
    private Integer selectedRoomId = null;
    private BigDecimal selectedRoomPrice = BigDecimal.ZERO;

    public FormBooking(User user) {
        initComponents();
        this.currentUser = user;
        setLocationRelativeTo(null);
        loadKamarKosong();
        setupListeners();
        
    }
    
    private void loadKamarKosong() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblKamarKosong.getModel();
            model.setRowCount(0);
            for (Room r : roomDAO.getKamarKosong()) {
                model.addRow(new Object[]{
                    r.getId(),
                    r.getNomorKamar(),
                    r.getTipe(),
                    r.getHarga(),
                    r.getStatus()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load kamar: " + e.getMessage());
        }
    }

    private void setupListeners() {
        tblKamarKosong.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tblKamarKosong.getSelectedRow() >= 0) {
                int row = tblKamarKosong.getSelectedRow();
                
                Object idObj = tblKamarKosong.getValueAt(row, 0);
                selectedRoomId = (idObj instanceof Integer)
                        ? (Integer) idObj
                        : Integer.parseInt(idObj.toString());
                Object hargaObj = tblKamarKosong.getValueAt(row, 3);
                double hargaDouble = (hargaObj instanceof Double)
                        ? (Double) hargaObj
                        : Double.parseDouble(hargaObj.toString());
                
                selectedRoomPrice = BigDecimal.valueOf(hargaDouble);
                txtHarga.setText(String.valueOf(hargaDouble));
                hitungTotalOtomatis();
            }
        });
        
        txtLama.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { hitungTotalOtomatis(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { hitungTotalOtomatis(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { hitungTotalOtomatis(); }
        });
    }

    private void hitungTotalOtomatis() {
        try {
            double harga = Double.parseDouble(txtHarga.getText());
            int lama = Integer.parseInt(txtLama.getText());
            double total = harga * lama;
            txtTotal.setText(String.valueOf(total));
        } catch (NumberFormatException ex) {
            txtTotal.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKamarKosong = new javax.swing.JTable();
        labNama = new javax.swing.JLabel();
        labCheckin = new javax.swing.JLabel();
        labLama = new javax.swing.JLabel();
        labHarga = new javax.swing.JLabel();
        labTotal = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtCheckin = new javax.swing.JTextField();
        txtLama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKamarKosong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "ID", "Nomor", "Tipe", "Harga", "Status" }
        ) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }}
        );
        jScrollPane1.setViewportView(tblKamarKosong);

        labNama.setText("Nama");

        labCheckin.setText("Check In");

        labLama.setText("Lama");

        labHarga.setText("Harga");

        labTotal.setText("Total");

        txtCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckinActionPerformed(evt);
            }
        });

        txtHarga.setEditable(false);

        txtTotal.setEditable(false);

        btnSimpan.setText("Check In");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labLama)
                            .addComponent(labCheckin)
                            .addComponent(labNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(txtCheckin)
                            .addComponent(txtLama))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labHarga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHarga))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labCheckin)
                            .addComponent(txtCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labLama)
                            .addComponent(txtLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labTotal)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            
            if (txtNama.getText().trim().isEmpty() ||
                    txtCheckin.getText().trim().isEmpty() ||
                    txtLama.getText().trim().isEmpty()) {
                
                JOptionPane.showMessageDialog(this, "Semua field wajib diisi");
                return;
            }
            
            if (selectedRoomId == null) {
                JOptionPane.showMessageDialog(this, "Pilih kamar terlebih dahulu");
                return;
            }
            
            int lama;
            try {
                lama = Integer.parseInt(txtLama.getText().trim());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Lama menginap harus angka");
                return;
            }
            
            if (lama <= 0) {
                JOptionPane.showMessageDialog(this, "Lama menginap harus > 0");
                return;
            }
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate tgl;
            
            try {
                tgl = LocalDate.parse(txtCheckin.getText().trim(), formatter);
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "Format tanggal harus yyyy-MM-dd");
                return;
            }
            
            BigDecimal total = selectedRoomPrice.multiply(BigDecimal.valueOf(lama));
            
            if (pelanggan == null) {
                PelangganDAO pDao = new PelangganDAO();
                pelanggan = pDao.getByUserId(currentUser.getIdUser());
                if (pelanggan == null) {
                    JOptionPane.showMessageDialog(this, "Data pelanggan tidak ditemukan. Lengkapi data di menu pelanggan dulu.");
                    return;
                }
            }

        
        Reservasi r = new Reservasi();
        r.setIdPelanggan(pelanggan.getIdPelanggan());
        r.setIdUser(currentUser.getIdUser());
        r.setIdRoom(selectedRoomId);
        r.setTanggal(Date.valueOf(tgl));
        r.setLamaMenginap(lama);
        r.setTotalHarga(total);
        r.setStatus("Menunggu");  // pending

        ReservasiDAO dao = new ReservasiDAO();
        dao.insertBooking(r);

        JOptionPane.showMessageDialog(this, "Booking berhasil disimpan, menunggu konfirmasi admin");

        new FormPelanggan(currentUser).setVisible(true);
        dispose();

    } catch (Exception e) {
        
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new FormPelanggan(currentUser).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckinActionPerformed

    /**
     * @param args the command line arguments
     */
    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(FormBooking.class.getName());
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormBooking(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCheckin;
    private javax.swing.JLabel labHarga;
    private javax.swing.JLabel labLama;
    private javax.swing.JLabel labNama;
    private javax.swing.JLabel labTotal;
    private javax.swing.JTable tblKamarKosong;
    private javax.swing.JTextField txtCheckin;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtLama;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
